### ISSUE TITLE
Working with data #2

### ISSUE THREAD

**Issue by mgrant46** [callysto/data-science-and-artificial-intelligence#1]
https://github.com/callysto/data-science-and-artificial-intelligence/blob/main/02-working-with-data.ipynb

I like that you included an extra cell for students to complete their exercises 

Suggested sections 
Part 1: Basic Dataframes Commands
Part 2: Working with Conditions 
- [x] I think it is important to mention that python count starts at zero (at the beginning somewhere)
- [x] maybe include somewhere the user can paste and copy the codes, as it makes it easier 
- [x] wondering if we should include an "debugging" exercise? Then the user can see what a python error looks like and they can troubleshoot the issue themselves. As I see this intimidates students when they an error message. 
- [x] At the end: Your assignment is to copy the code that you wrote for the exercises (spelling correction) in this notebook, and paste it into a document to hand in. What do you need mean by document? A new notebook or google document? Maybe suggest to name the notebook, for example DS and AI Working Notebook. Even better, have a GIF showing what you mean!

**Comment by misterhay** [comment]
Suggestions incorporated, thank you
