### ISSUE TITLE
Statistics #3

### ISSUE THREAD

**Issue by mgrant46** [callysto/data-science-and-artificial-intelligence#3]
https://github.com/callysto/data-science-and-artificial-intelligence/blob/main/03-statistics.ipynb

What I find is the students just run through this information with understand the reason or the purpose of running these stats. For example, what is is important we find the weight in Kg. _most pet foods instructions is based on kgs, as well in Canada and the rest of the world measures in metric system_

Maybe give them a scenario question: _You are needing to order dog food. Should you use the mean or max values to help you order dog food. Show the calculation and example why you picked this value._

For exercise 1 and 2: Ask them to give an example why this information is important to calculate in real life?

**Comment by misterhay** [comment]
Great ideas, I've incorporated them into notebooks 2 and 3
