### ISSUE TITLE
Statistics #3

### ISSUE THREAD

**Issue by mgrant46** [callysto/data-science-and-artificial-intelligence#4]
Notebook https://github.com/callysto/data-science-and-artificial-intelligence/blob/main/02-working-with-data.ipynb

- [x] Include a definition of Statistics 

_Statistics encompasses a variety of techniques employed to gather, arrange, examine, showcase, and decipher data._

What is statistics? at the beginning? I have created a word cloud (I can edit this word cloud)

![Stats word cloud](https://github.com/callysto/data-science-and-artificial-intelligence/assets/108431999/a9858c9a-40d8-473d-8528-b40151f5e4e8)

- [x] Include this video before introducing the code for mean, medium. Not sure if you can set it to stop at .50sec 
https://www.youtube.com/watch?v=zOYVZtTIjBA&t=49s

**Comment by misterhay** [comment]
I've added a definition of statistics including a link to that video. Not sure about adding the word cloud, but we can chat about that.
