### ISSUE TITLE
Training the Ai 

### ISSUE THREAD

**Issue by mgrant46** [callysto/data-science-and-artificial-intelligence#8]
https://github.com/callysto/data-science-and-artificial-intelligence/blob/main/11-training-ai.ipynb

1. Should we identify how many cat and dog images the user should downlaod to train their model? 5? 10? 
2. Getting an error message when linking on the hyper link to step 6 and unable to load my model 

![Screenshot 2023-06-13 at 2 49 37 PM](https://github.com/callysto/data-science-and-artificial-intelligence/assets/108431999/e8f04d70-06f0-4174-9fb1-ef6fea24f6dc)

**Comment by misterhay** [comment]
The instructions said "Try to have at least six of each", but I've updated it to 10 in the actual steps.

I've also updated the instructions for uploading to the current folder. Clicking the link works for me on the Callysto Hub, but clicking the logo at the top left will also work.
