### ISSUE TITLE
Getting Data 

### ISSUE THREAD

**Issue by mgrant46** [callysto/data-science-and-artificial-intelligence#9]
https://github.com/callysto/data-science-and-artificial-intelligence/blob/main/12-getting-data.ipynb

1. wondering if this notebook should go after primary data? It seems like a better flow, then going after AI 
since the other notebook is called "primary data", should this one be called "secondary data" ? 
2. Getting an error and cannot proceed 
![Screenshot 2023-06-13 at 3 10 19 PM](https://github.com/callysto/data-science-and-artificial-intelligence/assets/108431999/1c72f3cb-690a-4bbd-820a-967064b8502d)

**Comment by misterhay** [comment]
Maybe we should call this notebook "Getting More Data" or "Webscraping and APIs".

Good catch on the Wikipedia error, the page changed. I've updated the code to make it a little more resilient.
